name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main # Replace 'main' with your default branch if different
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your preferred Node.js version

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8 # Or your preferred pnpm version

      - name: Install dependencies
        run: pnpm install

      - name: Build Next.js app
        run: pnpm build # This assumes your build script in package.json is 'next build'

      - name: Add .nojekyll file
        run: touch ./out/.nojekyll

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 